server:
  port: 8088
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/isc?characterEncoding=utf8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    tomcat:
      max-active: 20
  redis:
    host: localhost
    port: 16666
    database: 1
    timeout: 3000
    password: x33+esaC
    pool: 
      max-active: 8
      max-wait: -1
      max-idle: 8
      min-idle: 0
      
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
        
myconfg: 
  servername: goe-server
  ishave: true

bonus: 
  percentage: 
     manageCostPercentage: 0.1
     bonusNumberPercentage: 0.7
     productCoinNumberPercentage: 0.2
     consumeCoinUnitPrice: 680
     reconsumeCoinUnitPrice: 480
     drawCostPercentage: 10

login: 
  expireTime: 30
  useInterceptor: false

